blank_issues_enabled: true
contact_links:
    - name: zksync-developers Discussion
      url: https://github.com/zkSync-Community-Hub/zkync-developers/discussions
      about: Please provide feedback, and ask questions here.
    - name: zksync-cli documentation page
      url: https://era.zksync.io/docs/tools/zksync-cli
      about: Please refer to the documentation for immediate answers.