name: Tests

on: pull_request


jobs:
  preparation_and_running_tests:
    permissions:
      contents: read
    strategy:
      matrix:
        os: [
              ubuntu-latest,
              windows-latest,
              macos-latest
            ]
        node-version: ['18.17.1', '20.11.0'] # or 18.17.1
        tags: [
                "common.test.ts"
              ]
    runs-on: ${{ matrix.os }}
              
    name: 'Node ${{ matrix.node-version }} / ${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies and build
        run: |
          npm ci && npm run build
        
      - name: Run tests
        env: 
          CI: true
          E2E_TESTNET_PK: ${{ secrets.E2E_TESTNET_PK }}
        run: |
          npx jest --verbose --testPathPattern=${{ matrix.tags }}
        shell: bash
